### PR TITLE
Remove # from url before appending `/swagger.json`

### LINKED ISSUE #53: Reloading is broken by latest pull request #52
If you're exploring an API and try to reload, the page fails to load due to a JSON error:

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
```

This is because the code added in #52 blindly appends on `/swagger.json` to the current URL, which might be something like `http://localhost:8000/#!/pet/updatePet`; giving `http://localhost:8000/#!/pet/updatePet/swagger.json`.

A server seeing this URL will actually just return the `index.html` page which is not valid JSON.

### PR DESCRIPTION
**Pull request by Mechazawa**
Fixes #53

### CODE REVIEW

**Comment by AkashMalhotra** [comment]
I'm  still getting the following error after I applied your change. How do I fix it

GET http://localhost:8081//swagger.json 404 (Not Found)
spec-converter.js:60 Uncaught Can't read swagger JSON from http://localhost:8081//swagger.json

**Comment by Mechazawa** [comment]
The latest commit should fix it.

**Comment by AkashMalhotra** [comment]
Okay I'll do them manually in my file since this is not pushed to master yet.  Also, do you know how I can use this UI with multiple json/yaml files?

**Comment by Mechazawa** [comment]
@AkashMalhotra You can just clone my fork and then do `git checkout fix/53
`

**Pull request merged**
